name: Update GitHub Action Versions

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_UPDATER_TOKEN }}
      - uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.ACTIONS_UPDATER_TOKEN }}
